# Generated by Django 5.2.12 on 2026-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kishan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('age', models.IntegerField()),
                ('bio_data', models.TextField()),
            ],
        ),
    ]
