# Generated by Django 5.2.12 on 2026-06-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0002_kishan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spocmodificationdecision',
            name='auth_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='spoc/mod_letters/'),
        ),
        migrations.AlterField(
            model_name='spocteamapproval',
            name='auth_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='spoc/auth_letters/'),
        ),
    ]
