# Generated by Django 4.2.7 on 2026-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0003_alter_spocmodificationdecision_auth_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spocteamapproval',
            name='final_auth_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='spoc/final_auth_letters/'),
        ),
        migrations.AddField(
            model_name='spocteamapproval',
            name='final_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
