# Generated by Django 5.2.12 on 2026-04-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_remove_creativematerial_hackathon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='hackathon_logos/')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_letter', models.FileField(blank=True, null=True, upload_to='approvals/')),
                ('poster_launching_date', models.DateField(blank=True, null=True)),
                ('website_launching_date', models.DateField(blank=True, null=True)),
                ('registration_open', models.DateField(blank=True, null=True)),
                ('registration_close', models.DateField(blank=True, null=True)),
                ('round_1_name', models.CharField(default='Round 1', max_length=255)),
                ('round_1_start_date', models.DateField(blank=True, null=True)),
                ('round_1_end_date', models.DateField(blank=True, null=True)),
                ('round_2_name', models.CharField(default='Round 2', max_length=255)),
                ('round_2_start_date', models.DateField(blank=True, null=True)),
                ('round_2_end_date', models.DateField(blank=True, null=True)),
                ('round_3_name', models.CharField(default='Round 3', max_length=255)),
                ('round_3_start_date', models.DateField(blank=True, null=True)),
                ('round_3_end_date', models.DateField(blank=True, null=True)),
                ('round_4_name', models.CharField(default='Round 4', max_length=255)),
                ('round_4_start_date', models.DateField(blank=True, null=True)),
                ('round_4_end_date', models.DateField(blank=True, null=True)),
                ('round_5_name', models.CharField(default='Round 5', max_length=255)),
                ('round_5_start_date', models.DateField(blank=True, null=True)),
                ('round_5_end_date', models.DateField(blank=True, null=True)),
                ('min_team_size', models.IntegerField(default=1)),
                ('max_team_size', models.IntegerField(default=4)),
                ('number_of_mentors', models.IntegerField(default=0)),
                ('total_team_members', models.IntegerField(default=4)),
                ('number_of_rounds', models.IntegerField(default=1)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.superadminprofile')),
            ],
            options={
                'db_table': 'accounts_hackathon',
            },
        ),
        migrations.CreateModel(
            name='CreativeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='creatives/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_creativematerial',
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='problem_statements/pdfs/')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_problemstatement',
            },
        ),
    ]
