# Generated by Django 5.2.12 on 2026-04-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='created_by',
        ),
    ]
