# Generated by Django 4.2.7 on 2026-04-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_hackathon_created_by_round_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundMarkingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_others', models.BooleanField(default=False)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_parameters', to='events.hackathon')),
            ],
            options={
                'db_table': 'events_roundmarkingparameter',
            },
        ),
    ]
