# Generated by Django 4.2.7 on 2026-06-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_roundmarkingparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativematerial',
            name='landing_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='landing_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
