# Generated by Django 5.2.12 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_creativematerial_landing_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativematerial',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creativematerial',
            name='institute_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creativematerial',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='creatives/profile_pics/'),
        ),
        migrations.AddField(
            model_name='creativematerial',
            name='quote_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creativematerial',
            name='speaker_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
