# Generated by Django 4.2.7 on 2026-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_creativematerial_voice_inspiration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativematerial',
            name='display_priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority order 1-10 for Voice of Inspiration. 0 means no priority.'),
        ),
    ]

