# Generated by Django 5.2.12 on 2026-06-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_creativematerial_display_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativematerial',
            name='material_type',
            field=models.CharField(db_column='material_type', default='creative', max_length=50),
        ),
    ]
