# Generated by Django 4.2.7 on 2026-06-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_creativematerial_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='event_logo',
            field=models.ImageField(blank=True, help_text='Event logo displayed on the right side of the landing page navbar.', null=True, upload_to='hackathon_logos/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hero_banner',
            field=models.ImageField(blank=True, help_text='Background banner image for the hero section on the landing page.', null=True, upload_to='hackathon_banners/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='platform_logo',
            field=models.ImageField(blank=True, help_text='HackNexus/platform logo displayed on the left side of the landing page navbar.', null=True, upload_to='hackathon_logos/'),
        ),
        migrations.CreateModel(
            name='HackathonDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('icon', models.CharField(default='🧩', max_length=10)),
                ('color', models.CharField(default='#eef2ff', max_length=20)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='events.hackathon')),
            ],
            options={
                'db_table': 'events_hackathondomain',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
