# Generated by Django 4.2.7 on 2026-06-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_hackathon_event_logo_hackathon_hero_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hackathon_banners/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_banners', to='events.hackathon')),
            ],
            options={
                'db_table': 'events_herobannerimage',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
    ]
