# Generated by Django 4.2.7 on 2026-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_herobannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmarkingparameter',
            name='cutoff_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The cutoff score required for this parameter', max_digits=5),
        ),
    ]
