# Generated by Django 4.2.7 on 2026-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_roundmarkingparameter_cutoff_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='round_1_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_1_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_2_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_2_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_3_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_3_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_4_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_4_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_5_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_5_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
