# Generated by Django 4.2.7 on 2026-07-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_hackathon_round_1_type_hackathon_round_1_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('name', models.CharField(help_text='Team label, e.g. Panel A', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_teams', to='events.hackathon')),
            ],
            options={
                'db_table': 'events_juryteam',
                'ordering': ['round_number', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoundJuryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('num_jury_per_team', models.IntegerField(default=1, help_text='Number of jury members in each evaluation team')),
                ('num_experts_per_team', models.IntegerField(default=1, help_text='Number of experts in each evaluation team')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_configs', to='events.hackathon')),
            ],
            options={
                'db_table': 'events_roundjuryconfig',
                'unique_together': {('hackathon', 'round_number')},
            },
        ),
    ]
