# Generated by Django 4.2.7 on 2026-07-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_spocinvitation_city_spocinvitation_state'),
        ('events', '0013_juryteam_roundjuryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='juryteam',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='assigned_jury_teams', to='accounts.expertprofile'),
        ),
        migrations.AddField(
            model_name='juryteam',
            name='juries',
            field=models.ManyToManyField(blank=True, related_name='assigned_jury_teams', to='accounts.juryprofile'),
        ),
        migrations.AddField(
            model_name='juryteam',
            name='problem_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jury_teams', to='events.problemstatement'),
        ),
    ]
