# Generated by Django 4.2.7 on 2026-07-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_juryteam_experts_juryteam_juries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingSubParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_parameters', to='events.roundmarkingparameter')),
            ],
            options={
                'db_table': 'events_markingsubparameter',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
