# Generated by Django 4.2.7 on 2026-07-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_markingsubparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='round_1_total_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_2_total_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_3_total_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_4_total_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_5_total_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='markingsubparameter',
            name='cutoff_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The score for this sub-parameter', max_digits=5),
        ),
    ]
