# Generated by Django 4.2.7 on 2026-07-28 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_hackathon_round_1_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='current_jury_round',
            field=models.IntegerField(default=1, help_text='The round for which jury panels can currently be created. Advances when admin promotes teams.'),
        ),
        migrations.AddField(
            model_name='roundjuryconfig',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When True, no new panels can be created and assignments are frozen for this round.'),
        ),
        migrations.AddField(
            model_name='roundjuryconfig',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundjuryconfig',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_jury_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
