# Generated by Django 4.2.7 on 2026-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_current_jury_round_and_round_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundjuryconfig',
            name='alter_assignment',
            field=models.BooleanField(default=False, help_text='When True, the round robin assignment order of teams to panels is altered.'),
        ),
    ]
