# Generated by Django 4.2.7 on 2026-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_roundjuryconfig_alter_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundjuryconfig',
            name='alter_offset',
            field=models.IntegerField(default=0, help_text='The rotational offset used to alter the round robin team panel assignment order.'),
        ),
    ]
