# Generated by Django 4.2.7 on 2026-08-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_roundjuryconfig_alter_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundjuryconfig',
            name='has_assigned_teams',
            field=models.BooleanField(default=False, help_text='When True, team panel assignments have been initiated and saved for the round.'),
        ),
        migrations.AddField(
            model_name='roundmarkingparameter',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='The maximum marks (total marks) allowed for this parameter', max_digits=5),
        ),
    ]
