# Generated by Django 4.2.7 on 2026-08-01 09:12

from django.db import migrations

def populate_has_assigned_teams(apps, schema_editor):
    RoundJuryConfig = apps.get_model('events', 'RoundJuryConfig')
    TeamEvaluationAssignment = apps.get_model('features', 'TeamEvaluationAssignment')

    for config in RoundJuryConfig.objects.all():
        # Check if there are any TeamEvaluationAssignment rows with assigned panels for this round & hackathon
        has_assignments = TeamEvaluationAssignment.objects.filter(
            team__hackathon=config.hackathon,
            round_number=config.round_number,
            assigned_panel__isnull=False
        ).exists()
        if has_assignments:
            config.has_assigned_teams = True
            config.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_roundjuryconfig_has_assigned_teams_and_more'),
        ('features', '0021_faqitem'),
    ]

    operations = [
        migrations.RunPython(populate_has_assigned_teams),
    ]
