# Generated by Django 4.2.7 on 2026-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20260801_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundjuryconfig',
            name='is_team_locked',
            field=models.BooleanField(default=False, help_text='When True, team assignments are locked for this round.'),
        ),
    ]
