# Generated by Django 4.2.7 on 2026-05-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0010_remove_teamevaluationassignment_expert_and_more'),
        ('events', '0004_roundmarkingparameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='events.roundmarkingparameter')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='features.team')),
            ],
            options={
                'db_table': 'jury_teamevaluation',
                'ordering': ['team', 'round_number', 'parameter'],
                'unique_together': {('team', 'round_number', 'evaluator', 'parameter')},
            },
        ),
    ]
