# Generated by Django 4.2.7 on 2026-05-12 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_remove_teamevaluationassignment_expert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_sent_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_messages', to='features.team')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('testimonial_video', models.FileField(blank=True, null=True, upload_to='jury/testimonials/')),
                ('bank_account_holder', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('ifsc_code', models.CharField(blank=True, max_length=32)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='jury/bank_docs/')),
                ('payment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jury_evaluatorprofile',
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
    ]
