# Generated by Django 5.2.12 on 2026-05-16 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0002_jurymessage_evaluatorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorTravelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('journey_date', models.DateField()),
                ('travel_mode', models.CharField(choices=[('train', 'Train'), ('bus', 'Bus'), ('flight', 'Flight'), ('car', 'Car'), ('other', 'Other')], default='train', max_length=20)),
                ('traveler_name', models.CharField(blank=True, max_length=255)),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('ticket_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ticket_file', models.FileField(blank=True, null=True, upload_to='jury/travel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_travel_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jury_evaluatortraveldetail',
                'ordering': ['-journey_date', '-created_at'],
            },
        ),
    ]
