# Generated by Django 4.2.7 on 2026-07-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0020_teamevaluationassignment_assigned_panel'),
        ('events', '0016_hackathon_round_1_total_marks_and_more'),
        ('jury', '0003_evaluatortraveldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSubParameterEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_sub_evaluations', to=settings.AUTH_USER_MODEL)),
                ('sub_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='events.markingsubparameter')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_evaluations', to='features.team')),
            ],
            options={
                'db_table': 'jury_teamsubparameterevaluation',
                'ordering': ['team', 'round_number', 'sub_parameter'],
                'unique_together': {('team', 'round_number', 'evaluator', 'sub_parameter')},
            },
        ),
    ]
