# Generated by Django 4.2.7 on 2026-04-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_executiveprofile_institution_juryprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='approval_letter',
            field=models.FileField(blank=True, null=True, upload_to='approvals/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='number_of_mentors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='poster_launching_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_1_name',
            field=models.CharField(default='Round 1', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_1_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_2_name',
            field=models.CharField(default='Round 2', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_2_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_3_name',
            field=models.CharField(default='Round 3', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_3_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_4_name',
            field=models.CharField(default='Round 4', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_4_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_5_name',
            field=models.CharField(default='Round 5', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_5_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='total_team_members',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='website_launching_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreativeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='creatives/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='accounts.hackathon')),
            ],
        ),
    ]
