# Generated by Django 4.2.7 on 2026-04-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hackathon_approval_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='round_1_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_2_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_3_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_4_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_5_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
