# Generated by Django 4.2.7 on 2026-04-02 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hackathon_round_1_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
