# Generated by Django 4.2.7 on 2026-04-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_problemstatement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='problem_statements/pdfs/'),
        ),
    ]
