# Generated by Django 4.2.7 on 2026-04-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
