# Generated by Django 4.2.7 on 2026-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_problemstatement_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativematerial',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creativematerial',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
