# Generated by Django 4.2.7 on 2026-04-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teamregistration_teamdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('role_description', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('assigned_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.venue')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='accounts.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='VenueFoodRefreshment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('menu_details', models.TextField(blank=True)),
                ('headcount_estimation', models.IntegerField(default=0)),
                ('cost_estimation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_refreshments', to='accounts.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_letter', models.FileField(blank=True, null=True, upload_to='venue/confirmations/')),
                ('allocated_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_allocations', to='accounts.hackathon')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255)),
                ('amount_pledged', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='accounts.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('infrastructure_readiness', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_plans', to='accounts.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=20)),
                ('category', models.CharField(choices=[('Team & Jury travel', 'Team & Jury travel Expenses'), ('Officials Travel', 'Officials Travel expenses'), ('Accommodation', 'Accommodation Expenses'), ('Printing & Stationary', 'Printing & Stationary Expenses'), ('Trophy and Awards', 'Trophy and Awards Expenses'), ('Food and refreshment', 'Food and refreshment'), ('Honorarium', 'Honorarium Expenses'), ('Other', 'Other Expenses')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.hackathon')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.hackathon')),
            ],
        ),
    ]
