# Generated by Django 5.2.12 on 2026-04-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_volunteerassignment_venuefoodrefreshment_and_more'),
    ]

    # NOTE: This migration physically drops `created_by` from Hackathon and
    # `hackathon` from CreativeMaterial / ProblemStatement. Those three models
    # are immediately re-adopted by the `events` app (events/0001_initial),
    # which re-adds the dropped FK columns. This migration is already applied in
    # existing databases, so its physical effect must NOT change -- the events
    # app is written to reconcile whatever schema this migration leaves behind,
    # which keeps fresh installs and already-deployed databases on the same path.
    operations = [
        migrations.RemoveField(
            model_name='creativematerial',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='eventbudget',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='problemstatement',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='hackathon',
        ),
    ]
