# Generated by Django 5.2.12 on 2026-04-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_creativematerial_hackathon_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spocinvitation',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.hackathon'),
        ),
        # Drop the composite unique constraints BEFORE removing their member
        # fields, otherwise Django cannot resolve the columns of the index it
        # needs to drop (FieldDoesNotExist on a fresh database).
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='teammentor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteerassignment',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='venueallocation',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='logisticsplan',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='sponsorshipfund',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='team',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='team',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='teamstatuslog',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammentor',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='created_team',
        ),
        migrations.RemoveField(
            model_name='teamdocument',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamdocument',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='teamdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teammentor',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='teamstatuslog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='volunteerassignment',
            name='assigned_venue',
        ),
        migrations.RemoveField(
            model_name='venueallocation',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='venuefoodrefreshment',
            name='venue',
        ),
        # Hackathon, ProblemStatement and CreativeMaterial have been re-adopted
        # by the events app (see events/0001_initial) and KEEP their physical
        # tables. Remove the old accounts-app models from Django's state only --
        # do NOT issue DROP TABLE, otherwise the events-owned tables vanish.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CreativeMaterial',
                ),
                migrations.DeleteModel(
                    name='Hackathon',
                ),
                migrations.DeleteModel(
                    name='ProblemStatement',
                ),
            ],
            database_operations=[],
        ),
        # The models below are genuinely removed -- drop their tables for real.
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.DeleteModel(
            name='EventBudget',
        ),
        migrations.DeleteModel(
            name='FinancialTransaction',
        ),
        migrations.DeleteModel(
            name='LogisticsPlan',
        ),
        migrations.DeleteModel(
            name='SponsorshipFund',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamDocument',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TeamMentor',
        ),
        migrations.DeleteModel(
            name='TeamRegistration',
        ),
        migrations.DeleteModel(
            name='TeamStatusLog',
        ),
        migrations.DeleteModel(
            name='VolunteerAssignment',
        ),
        migrations.DeleteModel(
            name='VenueAllocation',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueFoodRefreshment',
        ),
    ]
