# Generated by Django 4.2.7 on 2026-05-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_roundmarkingparameter'),
        ('accounts', '0019_jury_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='invited', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, help_text='Affiliated institution / company', max_length=255)),
                ('designation', models.CharField(blank=True, help_text='Job title / designation', max_length=255)),
                ('domain', models.CharField(blank=True, help_text='Area of expertise / judging domain', max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, help_text='Short professional bio')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='expert_id_proofs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='expert_photos/')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_expert_invitation', to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.hackathon')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
