# Generated by Django 4.2.7 on 2026-07-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_inappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='spocinvitation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spocinvitation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
