# Generated by Django 4.2.7 on 2026-09-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_spocinvitation_city_spocinvitation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('spoc', 'SPOC'), ('jury', 'Jury'), ('expert', 'Expert')], max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(choices=[('initial_submission', 'Initial Submission'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved')], max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='accounts.expertinvitation')),
                ('jury_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='accounts.juryinvitation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_reviews', to=settings.AUTH_USER_MODEL)),
                ('spoc_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='accounts.spocinvitation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role_type', 'created_at'], name='accounts_in_role_ty_a3f311_idx'), models.Index(fields=['spoc_invitation'], name='accounts_in_spoc_in_77859f_idx'), models.Index(fields=['jury_invitation'], name='accounts_in_jury_in_bccbaa_idx'), models.Index(fields=['expert_invitation'], name='accounts_in_expert__16d56f_idx')],
            },
        ),
    ]
