# Generated by Django 4.2.7 on 2026-04-29 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0007_teamregistration_leader_details'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTravelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('journey_date', models.DateField()),
                ('travel_mode', models.CharField(choices=[('train', 'Train'), ('bus', 'Bus'), ('flight', 'Flight'), ('car', 'Car'), ('other', 'Other')], default='train', max_length=20)),
                ('traveler_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('ticket_file', models.FileField(blank=True, null=True, upload_to='team_travel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='features.teamregistration')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-journey_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('venue', 'Venue Admin'), ('health', 'Health Admin'), ('grievance', 'Grievance Admin'), ('logistics', 'Logistics Admin'), ('spoc', 'SPOC'), ('mentor', 'Mentor'), ('general', 'General Support')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='team_support/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('admin_reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='features.teamregistration')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
