# Generated by Django 4.2.7 on 2026-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teamtraveldetail_teamsupportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtraveldetail',
            name='ticket_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teamtraveldetail',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
