# Generated by Django 5.2.12 on 2026-04-10 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_remove_creativematerial_hackathon_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('rulebook', 'Rulebook'), ('dataset', 'Dataset'), ('api_doc', 'API Documentation'), ('reference', 'Reference Material'), ('guideline', 'Guideline'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documentation/')),
                ('external_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='events.hackathon')),
                ('problem_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation', to='events.problemstatement')),
            ],
            options={
                'db_table': 'accounts_documentation',
            },
        ),
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_eventbudget',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=20)),
                ('category', models.CharField(choices=[('Team & Jury travel', 'Team & Jury travel Expenses'), ('Officials Travel', 'Officials Travel expenses'), ('Accommodation', 'Accommodation Expenses'), ('Printing & Stationary', 'Printing & Stationary Expenses'), ('Trophy and Awards', 'Trophy and Awards Expenses'), ('Food and refreshment', 'Food and refreshment'), ('Honorarium', 'Honorarium Expenses'), ('Other', 'Other Expenses')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.hackathon')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_financialtransaction',
            },
        ),
        migrations.CreateModel(
            name='LogisticsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('infrastructure_readiness', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_plans', to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_logisticsplan',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='podcasts/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='podcast_thumbs/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='events.hackathon')),
                ('problem_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='events.problemstatement')),
            ],
            options={
                'db_table': 'accounts_podcast',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255)),
                ('amount_pledged', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_sponsorshipfund',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hackathon')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.institution')),
                ('problem_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.problemstatement')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_team',
            },
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('members_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('suspension_note', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_registration', to='features.team')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='events.hackathon')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.institution')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mentorprofile')),
                ('problem_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.problemstatement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_reviews', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_teamregistration',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('project', 'Project File'), ('presentation', 'Presentation'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='team_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='features.team')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='features.teamregistration')),
            ],
            options={
                'db_table': 'accounts_teamdocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(choices=[('registered', 'Registered'), ('pending_mentor', 'Pending Mentor Verification'), ('mentor_approved', 'Mentor Approved'), ('mentor_rejected', 'Mentor Rejected'), ('pending_spoc', 'Pending SPOC Verification'), ('spoc_approved', 'SPOC Approved / Active'), ('spoc_rejected', 'SPOC Rejected'), ('submitted', 'Submission Done'), ('evaluated', 'Evaluated'), ('disqualified', 'Disqualified')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='features.team')),
            ],
            options={
                'db_table': 'accounts_teamstatuslog',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_venue',
            },
        ),
        migrations.CreateModel(
            name='VenueAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_letter', models.FileField(blank=True, null=True, upload_to='venue/confirmations/')),
                ('allocated_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_allocations', to='events.hackathon')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='features.venue')),
            ],
            options={
                'db_table': 'accounts_venueallocation',
            },
        ),
        migrations.CreateModel(
            name='VenueFoodRefreshment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('menu_details', models.TextField(blank=True)),
                ('headcount_estimation', models.IntegerField(default=0)),
                ('cost_estimation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_refreshments', to='features.venue')),
            ],
            options={
                'db_table': 'accounts_venuefoodrefreshment',
            },
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('role_description', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('assigned_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='features.venue')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='events.hackathon')),
            ],
            options={
                'db_table': 'accounts_volunteerassignment',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_team', models.CharField(blank=True, default='Member', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='features.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_teammember',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TeamMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mentorprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_mentors', to='features.team')),
            ],
            options={
                'db_table': 'accounts_teammentor',
                'unique_together': {('team', 'mentor')},
            },
        ),
    ]
