# Generated by Django 5.2.12 on 2026-04-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='created_by',
        ),
    ]
