# Generated by Django 5.2.12 on 2026-04-20 04:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_team_declared_member_count_team_leader_aadhaar_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='contact_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='event_date',
            field=models.CharField(blank=True, help_text='e.g. Mar 20-22, 2026', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='facilities',
            field=models.JSONField(blank=True, default=list, help_text='List of facility strings'),
        ),
        migrations.AddField(
            model_name='venue',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
