# Generated by Django 5.2.12 on 2026-04-23 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_add_venue_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'accounts_documentation'
                              AND column_name = 'created_by_id'
                        ) THEN
                            ALTER TABLE accounts_documentation
                            ADD COLUMN created_by_id bigint NULL;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'acc_doc_created_by_id_fk'
                        ) THEN
                            ALTER TABLE accounts_documentation
                            ADD CONSTRAINT acc_doc_created_by_id_fk
                            FOREIGN KEY (created_by_id)
                            REFERENCES accounts_user (id)
                            ON DELETE SET NULL
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_indexes
                            WHERE tablename = 'accounts_documentation'
                              AND indexname = 'acc_doc_created_by_id_idx'
                        ) THEN
                            CREATE INDEX acc_doc_created_by_id_idx
                            ON accounts_documentation (created_by_id);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS acc_doc_created_by_id_idx;
                    ALTER TABLE accounts_documentation
                    DROP CONSTRAINT IF EXISTS acc_doc_created_by_id_fk;
                    ALTER TABLE accounts_documentation
                    DROP COLUMN IF EXISTS created_by_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='documentation',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
