# Generated by Django 5.2.12 on 2026-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_documentation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='leader_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
