# Generated by Django 5.2.12 on 2026-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_teamregistration_leader_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatuslog',
            name='new_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('pending_mentor', 'Pending Mentor Verification'), ('mentor_approved', 'Mentor Approved'), ('mentor_rejected', 'Mentor Rejected'), ('pending_spoc', 'Pending SPOC Verification'), ('spoc_approved', 'SPOC Approved / Active'), ('admin_approved', 'Admin Approved'), ('spoc_rejected', 'SPOC Rejected'), ('submitted', 'Submission Done'), ('evaluated', 'Evaluated'), ('disqualified', 'Disqualified')], max_length=50),
        ),
    ]
