# Generated by Django 4.2.7 on 2026-05-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_expertprofile_expertinvitation'),
        ('features', '0008_alter_teamstatuslog_new_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_expert', to='accounts.expertprofile')),
                ('jury_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_jury1', to='accounts.juryprofile')),
                ('jury_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_jury2', to='accounts.juryprofile')),
                ('jury_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_jury3', to='accounts.juryprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assignments', to='features.team')),
            ],
            options={
                'db_table': 'features_teamevaluationassignment',
                'unique_together': {('team', 'round_number')},
            },
        ),
    ]
