# Generated by Django 4.2.7 on 2026-05-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_expertprofile_expertinvitation'),
        ('features', '0009_teamevaluationassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamevaluationassignment',
            name='expert',
        ),
        migrations.AddField(
            model_name='teamevaluationassignment',
            name='expert_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_expert1', to='accounts.expertprofile'),
        ),
        migrations.AddField(
            model_name='teamevaluationassignment',
            name='expert_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_as_expert2', to='accounts.expertprofile'),
        ),
    ]
