# Generated by Django 4.2.7 on 2026-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_podcast_publication_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='landing_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='podcast',
            name='landing_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
