# Generated by Django 5.2.12 on 2026-06-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_documentation_landing_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='podcast_type',
            field=models.CharField(choices=[('podcast', 'Podcast'), ('expert_talk', 'Expert Talk')], default='podcast', max_length=50),
        ),
    ]
