# Generated by Django 5.2.12 on 2026-06-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_podcast_podcast_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader_aadhaar_proof',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='team_documents/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_college_id_proof',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='team_documents/college_ids/'),
        ),
        migrations.AlterField(
            model_name='teamdocument',
            name='file',
            field=models.FileField(max_length=255, upload_to='team_documents/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='aadhaar_proof',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='team_documents/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='college_id_proof',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='team_documents/college_ids/'),
        ),
    ]
