# Generated by Django 4.2.7 on 2026-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_alter_team_leader_aadhaar_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipfund',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sponsorshipfund',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/'),
        ),
    ]
