# Generated by Django 4.2.7 on 2026-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_sponsorshipfund_location_sponsorshipfund_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_round',
            field=models.IntegerField(default=1, help_text='The round this team is currently in'),
        ),
    ]
