# Generated by Django 4.2.7 on 2026-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0017_team_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='registration_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
