# Generated by Django 5.2.12 on 2026-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_teamregistration_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.CharField(blank=True, default='Featured', max_length=100),
        ),
    ]
