# Generated by Django 4.2.7 on 2026-07-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_markingsubparameter'),
        ('features', '0019_podcast_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevaluationassignment',
            name='assigned_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_team_evaluations', to='events.juryteam'),
        ),
    ]
