# Generated by Django 4.2.7 on 2026-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0021_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='bank_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
